import React from 'react';
import { Routes, Route, Navigate, useLocation } from 'react-router-dom';
import Sidebar from './layouts/Sidebar';
import TopHeader from './layouts/TopHeader';
import DashboardPage from './pages/DashboardPage';
import LiveMonitoringPage from './pages/LiveMonitoringPage';
import CameraVisionPage from './pages/CameraVisionPage';
import AIAnalyticsPage from './pages/AIAnalyticsPage';
import EventsAlertsPage from './pages/EventsAlertsPage';
import MaintenancePage from './pages/MaintenancePage';
import SystemHealthPage from './pages/SystemHealthPage';
import SettingsPage from './pages/SettingsPage';
import { useTelemetry } from './hooks/useTelemetry';
import { useEvents } from './hooks/useEvents';
import { exportTelemetryCSV } from './services/exportService';

const PAGE_TITLES: Record<string, string> = {
  '/dashboard':   'Dashboard',
  '/monitoring':  'Live Monitoring',
  '/camera':      'Camera Vision',
  '/ai':          'AI Analytics',
  '/events':      'Events & Alerts',
  '/maintenance': 'Predictive Maintenance',
  '/system':      'System Health',
  '/settings':    'Settings',
};

export default function App() {
  const location = useLocation();
  const telemetry = useTelemetry();
  const { events, notifications, unreadCount, acknowledgeEvent, resolveEvent, markNotificationRead, markAllRead } = useEvents(
    telemetry.riskAnalysis,
    telemetry.current,
  );

  const pageTitle = PAGE_TITLES[location.pathname] ?? 'Dashboard';

  function handleAcknowledge() {
    const activeEvent = events.find(e => e.status === 'active');
    if (activeEvent) acknowledgeEvent(activeEvent.id);
  }

  return (
    <div style={{
      display: 'flex',
      height: '100vh',
      overflow: 'hidden',
      background: 'var(--color-industrial-900)',
    }}>
      {/* Sidebar */}
      <Sidebar unreadCount={unreadCount} />

      {/* Main area */}
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden', minWidth: 0 }}>
        {/* Demo mode banner */}
        <div className="demo-banner" role="status" aria-live="polite">
          ⚗ SIMULATION / DEMO MODE — All sensor data is generated by the frontend simulation engine. Not from real ESP32 hardware.
        </div>

        {/* Top header */}
        <TopHeader
          pageTitle={pageTitle}
          riskAnalysis={telemetry.riskAnalysis}
          lastUpdateMs={telemetry.lastUpdateMs}
          notifications={notifications}
          unreadCount={unreadCount}
          scenario={telemetry.scenario}
          onScenarioChange={telemetry.setScenario}
          onMarkAllRead={markAllRead}
          onMarkRead={markNotificationRead}
          onExportTelemetry={() => exportTelemetryCSV(telemetry.history)}

          systemPower={telemetry.systemPower}
          startingStep={telemetry.startingStep}
          conveyorState={telemetry.conveyorState}
          selectedConveyorId={telemetry.selectedConveyorId}
          acceleration={telemetry.acceleration}
          beltOffset={telemetry.current?.beltOffset ?? 0}
          onConveyorChange={telemetry.setConveyor}
          onPowerToggle={telemetry.setSystemPower}
          onConveyorStateChange={telemetry.setConveyorState}
          onAccelerationChange={telemetry.setAcceleration}
        />

        {/* Page content */}
        <main style={{ flex: 1, overflowY: 'auto', overflowX: 'hidden' }}>
          <Routes>
            <Route path="/" element={<Navigate to="/dashboard" replace />} />
            <Route path="/dashboard"   element={<DashboardPage   telemetry={telemetry} events={events} onAcknowledge={handleAcknowledge} />} />
            <Route path="/monitoring"  element={<LiveMonitoringPage telemetry={telemetry} togglePause={telemetry.togglePause} />} />
            <Route path="/camera"      element={<CameraVisionPage  telemetry={telemetry} />} />
            <Route path="/ai"          element={<AIAnalyticsPage   telemetry={telemetry} />} />
            <Route path="/events"      element={<EventsAlertsPage  events={events} onAcknowledge={acknowledgeEvent} onResolve={resolveEvent} />} />
            <Route path="/maintenance" element={<MaintenancePage   telemetry={telemetry} events={events} />} />
            <Route path="/system"      element={<SystemHealthPage  telemetry={telemetry} />} />
            <Route path="/settings"    element={<SettingsPage />} />
            <Route path="*"            element={<Navigate to="/dashboard" replace />} />
          </Routes>
        </main>
      </div>
    </div>
  );
}
